[project]
name = "ax1-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jhc891108", email = "jhc891108@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ax1-1 = "ax1_1:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
